trigger:
- master

variables:
  tag: '$(Build.BuildId)'
  
pool: 
  name: default 
  demands: 
    - agent.name -equals eoc-controller
  
stages:
  - stage: Build
    displayName: Build Stage
    jobs:
     - job: Build
       displayName: Build job
       steps:
         - task: Docker@2
           inputs:
             containerRegistry: 'docker-hub'
             repository: 'eyesoncloud/azdevops'
             command: 'buildAndPush'
             Dockerfile: '**/Dockerfile'
             tags: 
               $(tag)
         - task: Bash@3
           displayName: Deploy to Kubernetes
           inputs:
             targetType: 'inline'
             script: |
               TAG=${BUILD_BUILDID}
               sed "s|tag|$TAG|g" deployment.yaml > deployment-processed.yaml
               kubectl apply -f deployment-processed.yaml
               kubectl rollout restart deployment/azdevops-deployment


