apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  labels:
    app: azdevops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azdevops
  template:
    metadata:
      labels:
        app: azdevops
    spec:
      containers:
        - name: azdevops
          image: eyesoncloud/azdevops:TAG_PLACEHOLDER
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: azdevops-service
spec:
  type: NodePort
  selector:
    app: azdevops
  ports:
    - port: 80          
      targetPort: 80     
      nodePort: 30036    
